Avoid trailing whitespaces
If the git diff command has a exit code 2 (meaning that there is a
trailing whitespace) the commit will be interrupted showing the occurences.

Fixes: stoqtech/squads/kazoo/tasks#5
Change-Id: I38ca988735ebc597f8f66fce794c6e012ab35e57

diff --git a/git-hooks/pre-commit b/git-hooks/pre-commit
--- a/git-hooks/pre-commit
+++ b/git-hooks/pre-commit
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+git diff --check --cached
+if [ $? -eq 2 ]; then
+  echo "Failed git diff --check. Please fix conflict markers and whitespace errors before committing."
+  exit 1
+fi
+
 set -e
 
 # pwd is already set to the project's root
